### ISSUE TITLE
Works great - for mail!

### ISSUE THREAD

**Issue by AMillott** [thepastafarian/New-Outlook-Killer#1]
@thepastafarian This is an excellent little application that does exactly what it says on the box.
It monitors the Windows Mail application and uninstalls New Outlook, however I am only using the Windows Calendar Application and it does not work for that :(

I have tried updating the "HxOutlook.exe" to "HxCalendarAppImm.exe" in NOK.py and rebuilding the EXE using Python, but I am a total novice with Python.
I managed to get the EXE to build using PyInstaller, but the new NOK EXE I create will not run :(

Are you able to create an alternate EXE, one that monitors for Mail and one for Calendar please? or looks for either application running?

**Comment by thepastafarian** [comment]
I never intended for it to be used with calendar but it shouldn't be very difficult to get NOK to work with it. I never use the calendar app so I'll have to mess around with it to see how it works first.

If I succeed I'll post it to github soon

-Pasta


-------- Original message --------
From: AMillott ***@***.***>
Date: 10/30/24 02:23 (GMT+02:00)
To: thepastafarian/New-Outlook-Killer ***@***.***>
Cc: thepastafarian ***@***.***>, Mention ***@***.***>
Subject: [thepastafarian/New-Outlook-Killer] Works great - for mail! (Issue #1)


@thepastafarian<https://github.com/thepastafarian> This is an excellent little application that does exactly what it says on the box.
It monitors the Windows Mail application and uninstalls New Outlook, however I am only using the Windows Calendar Application and it does not work for that :(

I have tried updating the "HxOutlook.exe" to "HxCalendarAppImm.exe" in NOK.py and rebuilding the EXE using Python, but I am a total novice with Python.
I managed to get the EXE to build using PyInstaller, but the new NOK EXE I create will not run :(

Are you able to create an alternate EXE, one that monitors for Mail and one for Calendar please? or looks for either application running?

**Comment by thepastafarian** [comment]
I just messed around with this a bit. NOK should automatically search for and uninstall new outlook regardless of which program initiates the install. Did you put a NOK shortcut in your startup folder?

**Comment by thepastafarian** [comment]
if not there should be instructions in the readme on how to do that. once that's done NOK should be consistently running in the background and constantly uninstalling outlook whenever it tries to reinstall.

Or are you trying to keep calendar from installing too?

**Comment by AMillott** [comment]
Yes, I have NOK in my startup folder. I can view status on the NOK Monitor and it says Mail App Status: Not Running. When I run the Windows Calendar app, it shows the same status. The Calendar app triggers New Outlook to install and it does not get uninstall by NOK.
Then I run the Windows Mail app and the NOK Monitor shows Mail App Status: Running and it will uninstall the New Outlook.

From what I could see in the Python code, it has;
```
# Mail app process name (this may vary, adjust if needed)
mail_app_process = "HxOutlook.exe"
scan_interval = 5  # Default scan interval in seconds
resource_usage = {"cpu": 0, "memory": 0}
```
and if it was also looking for 'HxCalendarAppImm.exe' it should detect the Calendar app too.

**Comment by thepastafarian** [comment]
Ok found the problem, latest release is up with support for Calendar. V1.1.0

**Comment by AMillott** [comment]
You, good sir, are a legend.
All working at my end :)
